# Generated by Django 4.1.4 on 2022-12-31 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_product',
            new_name='BankProduct',
        ),
        migrations.RenameModel(
            old_name='Monthly_check',
            new_name='MonthlyCheck',
        ),
        migrations.RenameModel(
            old_name='Payment_method',
            new_name='PaymentMethod',
        ),
    ]
