# Generated by Django 4.1.4 on 2023-01-10 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_rename_bank_product_bankproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name=datetime.date)),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('secure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.CharField(max_length=100)),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.entity')),
            ],
        ),
    ]
