# Generated by Django 4.1.4 on 2023-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0004_alter_transactioncontrol_bank_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncontrol',
            name='bank_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontrol',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontrol',
            name='secure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontrol',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
