# Generated by Django 4.1.4 on 2023-01-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0005_alter_transactioncontrol_bank_interest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionControl',
        ),
    ]
