# Generated by Django 4.1.4 on 2023-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0007_transactioncontrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankProduct',
            new_name='Products',
        ),
    ]
