# Generated by Django 4.1.4 on 2023-01-10 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking_app', '0010_remove_monthlycheck_id_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name=datetime.date)),
                ('reason', models.CharField(max_length=50)),
                ('transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('bank_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('secure', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name=datetime.date)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=50)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.category')),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.entity')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.paymentmethod')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.products')),
            ],
        ),
    ]
