# Generated by Django 4.1.4 on 2023-01-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncontrol',
            name='id_entity',
        ),
        migrations.CreateModel(
            name='FinancialProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.entity')),
            ],
        ),
        migrations.AddField(
            model_name='transactioncontrol',
            name='id_financial_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracking_app.financialproducts'),
            preserve_default=False,
        ),
    ]
