# Generated by Django 4.1.4 on 2023-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0012_remove_transactioncontrol_id_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproducts',
            name='product_type',
            field=models.TextField(choices=[('TC', 'Credit Card'), ('CA', 'Saving Accounts'), ('TD', 'Debit Card'), ('VC', 'Vehicle Loan'), ('INV', 'Investments'), ('OT', 'Others')], default=0),
            preserve_default=False,
        ),
    ]
