# Generated by Django 4.1.4 on 2023-01-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0013_financialproducts_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncontrol',
            name='id_financial_product',
        ),
        migrations.DeleteModel(
            name='FinancialProducts',
        ),
        migrations.DeleteModel(
            name='TransactionControl',
        ),
    ]
